export const Emojis: Map<string, string> = new Map<string, string>([
  ["canned", "🥫"],
  ["beans", "🫘"],
  ["falafel", "🧆"],
  ["curry rice", "🍛"],
  ["shrimp", "🦐"],
  ["squid", "🦑"],
  ["olive", "🫒"],
  ["bacon", "🥓"],
  ["egg", "🥚"],
  ["croissant", "🥐"],
  ["avocado", "🥑"],
  ["carrot", "🥕"],
  ["grapes ", "🍇"],
  ["melon", "🍈"],
  ["watermelon", "🍉"],
  ["tangerine", "🍊"],
  ["lemon", "🍋"],
  ["banana", "🍌"],
  ["pineapple", "🍍"],
  ["mango", "🥭"],
  ["red apple", "🍎"],
  ["green apple", "🍏"],
  ["pear", "🍐"],
  ["peach", "🍑"],
  ["cherry", "🍒"],
  ["strawberry", "🍓"],
  ["blueberry", "🫐"],
  ["kiwi", "🥝"],
  ["tomato", "🍅"],
  ["potato", "🥔"],
  ["bread", "🥖"],
  ["coconut", "🥥"],
  ["eggplant", "🍆"],
  ["corn", "🌽"],
  ["hot pepper", "🌶️"],
  ["bell pepper", "🫑"],
  ["lettuce", "🥬"],
  ["broccoli", "🥦"],
  ["garlic", "🧄"],
  ["onion", "🧅"],
  ["mushroom", "🍄"],
  ["cucumber", "🥒"],
  ["peanuts", "🥜"],
  ["flatbread", "🫓"],
  ["pretzel", "🥨"],
  ["bagel", "🥯"],
  ["pancakes", "🥞"],
  ["waffles", "🧇"],
  ["cheese", "🧀"],
  ["chicken", "🍗"],
  ["beef", "🥩"],
  ["pork", "🥩"],
  ["steak", "🥩"],
  ["hamburger", "🍔"],
  ["fries", "🍟"],
  ["pizza", "🍕"],
  ["hot dog", "🌭"],
  ["sandwich", "🥪"],
  ["taco", "🌮"],
  ["burrito", "🌯"],
  ["stuffed", "🥙"],
  ["fondue", "🫕"],
  ["salad", "🥗"],
  ["popcorn", "🍿"],
  ["butter", "🧈"],
  ["bento box", "🍱"],
  ["rice cracker", "🍘"],
  ["rice ball", "🍙"],
  ["rice", "🍚"],
  ["spaghetti", "🍝"],
  ["sweet potato", "🍠"],
  ["sushi", "🍣"],
  ["fried shrimp", "🍤"],
  ["fish cake", "🍥"],
  ["dumpling", "🥟"],
  ["fortune cookie", "🥠"],
  ["oyster", "🦪"],
  ["ice cream", "🍦"],
  ["doughnut", "🍩"],
  ["cookie", "🍪"],
  ["cake", "🎂"],
  ["pie", "🥧"],
  ["cupcake", "🧁"],
  ["chocolate", "🍫"],
  ["candy", "🍬"],
  ["lollipop", "🍭"],
  ["custard", "🍮"],
  ["honey", "🍯"],
  ["milk", "🥛"],
  ["coffee", "☕"],
  ["tea", "🫖"],
  ["sake", "🍶"],
  ["champagne", "🍾"],
  ["wine", "🍷"],
  ["cocktail", "🍸"],
  ["beer", "🍺"],
  ["bubble tea", "🧋"],
  ["juice", "🧃"],
  ["mate", "🧉"],
  // categories
  ["meat", "🥩"],
  ["vegetables", "🥕"],
  ["fruits", "🍎"],
  ["grains", "🌾"],
  ["dairy", "🥛"],
  ["beverages", "🥤"],
  ["sweets", "🍰"],
  ["snacks", "🍿"],
]);
