export enum NotificationType {
    FRIEND_REQUEST = 'FRIEND_REQUEST',
    FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
    CLAIM = 'CLAIM',
    CLAIM_ACCEPTED = 'CLAIM_ACCEPTED',
    EXPIRY = 'EXPIRY',
    GENERIC = 'GENERIC',
}